name = plutoniumships
title = Plutotnium's Ships
author = plutonium
description = Turn your constructions into boats or blimps and set off on the adventure aboard the ship of your dreams. 
version = 2.0
depends = default, wool, xdecor
